# argo/app-java-webservice.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-webservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Raju9347/Demo-Java-Webservice.git
    targetRevision: Feature/Testing
    path: K8s/helm
    helm:
      parameters:
        - name: image.repository
          value: 338034595180.dkr.ecr.us-west-2.amazonaws.com/demo-java-app
        - name: image.tag
          value: v1.0.61
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}        # or leave manual if you prefer
    syncOptions:
      - CreateNamespace=true
