apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-webservice.fullname" . }}
  labels:
    app: {{ include "java-webservice.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ include "java-webservice.name" . }}