name: CI
on:
  workflow_dispatch:
  push:
    branches: [ '**' ]

env:
#   EKS_CLUSTER_NAME: my-cluster-name
#   AWS_REGION: us-west-2
#   SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
#   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#   SONAR_USERNAME: ${{ secrets.SONAR_USERNAME }}
  REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  IMAGE_NAME: demo-java-app
  TAG: v1.0.${{ github.run_number }}   #v1.0.XXXXXX
#   TWISTLOCK_CONSOLE_URL: ${{ secrets.TWISTLOCK_CONSOLE_URL }}
#   TWISTLOCK_USERNAME: ${{ secrets.TWISTLOCK_USERNAME }}
#   TWISTLOCK_PASSWORD: ${{ secrets.TWISTLOCK_PASSWORD }}
#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#   SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}
    

jobs:
  MavenDockerBuild: 
    runs-on: self-hosted
    outputs:
     plan-artifact: Build-Test-Artifact

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Unit tests
        run: mvn -q -B test
      
      - name: Build with Maven
        run: mvn clean package

      - name: Lint (Checkstyle)
        run: mvn -q -B checkstyle:check || (echo "Lint issues found"; exit 1)

      - name: Docker Login and Build
        run: |
          docker login ${{ env.REGISTRY_URL }} -u ${{ env.REGISTRY_USERNAME }} -p ${{ env.REGISTRY_PASSWORD }}
          docker build -f Dockerfile -t ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.TAG }} .

      - name: Save image for scanning
        run: docker image save ${{ env.IMAGE_NAME }}:${{ env.TAG }} -o java-app.tar

      - name: Scan_with_Trivy
        id: Scan_with_Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          input: java-app.tar
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          ignore-unfixed: true

      - name: Docker_Image_push
        if: ${{ steps.Scan_with_Trivy.outcome == 'success' }}
        run: |
         docker login ${{ env.REGISTRY_URL }} -u ${{ env.REGISTRY_USERNAME }} -p ${{ env.REGISTRY_PASSWORD }}
         docker push ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.TAG }}
        
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-Test-Artifact

